# Generated by Django 4.1.5 on 2023-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
